// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwrR26kW_tePJi7AZwVZcyR5mUPDvl0QE',
    appId: '1:599512958839:web:ba05e8324362cad0760372',
    messagingSenderId: '599512958839',
    projectId: 'onye-development',
    authDomain: 'onye-development.firebaseapp.com',
    storageBucket: 'onye-development.appspot.com',
    measurementId: 'G-8KR83WFBT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEHXRoBQQhBWI7w5ihX_FV6GaadXKxiAI',
    appId: '1:599512958839:android:5bbb7953a89bf1e7760372',
    messagingSenderId: '599512958839',
    projectId: 'onye-development',
    storageBucket: 'onye-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPP4mTyCMhA49HwZgCxihPJ2UUByw-zwc',
    appId: '1:599512958839:ios:67a5e6dbde9976ba760372',
    messagingSenderId: '599512958839',
    projectId: 'onye-development',
    storageBucket: 'onye-development.appspot.com',
    iosClientId: '599512958839-vt1j949n65juq7nio2pim3eihssivcn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.onyeFrontEned',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPP4mTyCMhA49HwZgCxihPJ2UUByw-zwc',
    appId: '1:599512958839:ios:67a5e6dbde9976ba760372',
    messagingSenderId: '599512958839',
    projectId: 'onye-development',
    storageBucket: 'onye-development.appspot.com',
    iosClientId: '599512958839-vt1j949n65juq7nio2pim3eihssivcn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.onyeFrontEned',
  );
}
